
import os
from supabase import create_client

# Define Supabase credentials manually or load from env
url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_KEY")

if not url or not key:
    try:
        from dotenv import load_dotenv
        load_dotenv()
        url = os.getenv("SUPABASE_URL")
        key = os.getenv("SUPABASE_SERVICE_KEY")
    except ImportError:
        pass

if not url or not key:
    print("CRITICAL: Cannot connect to Supabase without URL and Service Key.")
    exit(1)

print("\n" + "="*50)
print("REQUIRED DATABASE UPDATE FOR CALENDAR EVENTS")
print("="*50)
print("Please run the following SQL in your Supabase SQL Editor to support the new Calendar Events feature:\n")

print("""
-- Create Calendar Events Table
CREATE TABLE IF NOT EXISTS calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    priority TEXT DEFAULT 'Medium', -- 'Normal', 'Medium', 'High'
    reminders JSONB DEFAULT '[]'::jsonb, -- e.g. ["same_day", "one_day_before"]
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT check_priority CHECK (priority IN ('Normal', 'Medium', 'High'))
);

-- Enable RLS
ALTER TABLE calendar_events ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own events" 
ON calendar_events FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own events" 
ON calendar_events FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own events" 
ON calendar_events FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own events" 
ON calendar_events FOR DELETE 
USING (auth.uid() = user_id);

-- Add 'Admin' view all policy if needed
-- (Optional: Admins might want to see team availability?)
-- For now keeping it private to user.
""")

print("\n" + "="*50)
